<?php
  function form_1_modal_page($js = NULL, $nid = NULL) {
    if($nid == NULL){
      return 'Node Error'
    }
    if($js){
      ctools_include('modal');
      ctools_include('ajax');
    }

    $node = node_lad($nde);
    $node_content = render(node_view($node,'teaser',NULL));

    return ctools_modal_render($node->title, $node_content);
    // $form['name'] = array(
    //   '#type' => 'textfield',
    //   '#title' => 'Your Name',
    //   '#maxlenght' => 30,
    //   '#required' => TRUE
    // );

    // $form['last_name'] = array(
    //   '#type' => 'textfield',
    //   '#type' => 'textfield',
    //   '#title' => 'Last name',
    //   '#required' => TRUE
    // );

    // $form['submit_button'] = array(
    //   '#type' => 'submit',
    //   '#value' => t('Submit'),
    // );

    return $form;
}

  function form_1_pre_render(&$views) {
    if($views->name == 'form_page'){
      ctools_include('ajax');
      ctools_include('ajax');
      ctools_modal_add_js();

      $form_style = array(
        'form-1-style' => array(
          'modalSize' => array(
            'type' => 'fixed',
            'width' => 600,
            'height' => 600,
            'addWidth' => 10,
            'addHeight' => 10,
            'contentRight' => 0,
            'contentBottom' => 0,
          ),
          'modalOptions' => array(
            'opacity' => .6,
            'background-color' => '#684C31',
          ),
          'animation' => 'fadeIn',
          'modalTheme' => 'form_1_modal',
          'throbber' => theme('image', array('path' => ctools_image_path('ajax-loader.gif', 'happy'), 'alt' => t('Loading...'), 'title' => t('Loading'))),
          'closeImage' => theme('image', array('path' => ctools_image_path('modal-close.png', 'happy'), 'alt' => t('Close window'), 'title' => t('Close window'))),
        ),
      );
      drupal_add_js($form_style,'setting');
      ctools_add_js('form_1','form_1');
    }
  }

  function form_1_form_validate($form, &$form_state) {

  }
  function form_1_form_submit($form, &$form_state) {

  }

  function form_1_menu(){
    $items = array();
    $items['forms/%ctools_s/%'] = array(
      'title' => 'Formula 1 subscription',
      'description' => 'Want to try racing with a F1 car?',
      'page callback' => 'form_1_modal_page',
      'page arguments' => array(1,2),
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM
    );

    dd("GNE");

    return $items;

  }

  function happy_theme() {
    return array(
      'views_view_fields__form' => array(
        'variables' => array('view' => NULL, 'options' => NULL, 'row' => NULL),
        'template' => 'views-view-fields--form',
        'base hook' => 'views_view_fields',
        'path' => drupal_get_path('module', 'Form_1') . '/theme',
      ),
    );
  }

  function form_1_preprocess_views_view_fields(&$vars) {
    if ($vars['view']->name == 'form_page') {
      ctools_include('ajax');
      ctools_include('modal');
      // The view has two fields, title (not linked and no styles added), and NID (again,
      // no style added. They are available here as $vars['fields']->title and
      // $vars['fields']->nid.
      $name = $vars['fields']['title']->content;
      // Create a path for the url that is like our hook_menu() declaration above.
      $href = 'forms/nojs/' . $vars['fields']['nid']->content;
      // Here's the ctools function that generates the trigger inside the link
      // ctools_modal_text_button($text, $dest, $alt, $class = '')
      // <a href="http://api.drupalize.me/api/drupal/function/ctools_modal_text_button/7">http://api.drupalize.me/api/drupal/function/ctools_modal_text_button/7</a>
      // IMPORTANT: Include ctools-modal-[your declared style name] as a class so
      // Ctools knows what Javascript settings to use in generating the modal:
      $vars['ctools_link'] = ctools_modal_text_button($name, $href, t('View node content for @name', array('@name' => $name)), 'ctools-modal-happy-modal-style');
    }
  }
